[package]
name = "bracket-parser"
version = "0.1.0"
edition = "2024"

# Define both library and binary targets
[lib]
name = "bracket_parser"
path = "src/lib.rs"

[[bin]]
name = "show_usage"
path = "src/main.rs"

[dependencies]
tree-sitter = "0.25.6"

[build-dependencies]
cc = "1.2.26"